server:
  port: 8050

spring:
  application:
    name: logger
  data:
    mongodb:
      uri: ${mongo_uri}
  rabbitmq:
    addresses: ${rabbit_uri}
    username: ${rabbit_username}
    password: ${rabbit_password}

rabbitmq:
  exchanges:
    internal: internal-logger.exchange
  queues:
    core-logger: core.queue
    placement-logger: placement.queue
    game-logger: game.queue
  routing-keys:
    internal-placement-logger: internal.placement-logger.routing-key
    internal-core-logger: internal.core-logger.routing-key
    internal-game-logger: internal.game-logger.routing-key
